In [3]:
import pandas as pd
df = pd.read_csv('task1.csv')
df.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M6A        North York  Lawrence Heights
6      M6A        North York    Lawrence Manor
7      M7A  Downtown Toronto      Queen's Park
8      M8A      Not assigned      Not assigned
9      M9A      Queen's Park      Not assigned

In [4]:
#!pip install geocoder

In [5]:
import geocoder

In [6]:
def get_latlng(postal_code):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Toronto, Ontario'.format(postal_code))
        lat_lng_coords = g.latlng
    return lat_lng_coords
    
get_latlng('M4G')

[43.70949500000006, -79.36398897099997]

In [9]:
postcodes = df['Postcode']    
coords = [ get_latlng(postcode) for postcode in postcodes.tolist() ]

In [13]:
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])
df['Latitude'] = df_coords['Latitude']
df['Longitude'] = df_coords['Longitude']
df.head(10)

  Postcode           Borough     Neighbourhood   Latitude  Longitude
0      M1A      Not assigned      Not assigned  43.648690 -79.385440
1      M2A      Not assigned      Not assigned  43.648690 -79.385440
2      M3A        North York         Parkwoods  43.752420 -79.329242
3      M4A        North York  Victoria Village  43.730600 -79.313265
4      M5A  Downtown Toronto      Harbourfront  43.650295 -79.359166
5      M6A        North York  Lawrence Heights  43.723270 -79.451286
6      M6A        North York    Lawrence Manor  43.723270 -79.451286
7      M7A  Downtown Toronto      Queen's Park  43.661150 -79.391715
8      M8A      Not assigned      Not assigned  43.648690 -79.385440
9      M9A      Queen's Park      Not assigned  43.662299 -79.528195

In [15]:
df[df.Postcode == 'M5G']
df.to_csv('task2.csv', index=False)

In [16]:
df.head(10)

  Postcode           Borough     Neighbourhood   Latitude  Longitude
0      M1A      Not assigned      Not assigned  43.648690 -79.385440
1      M2A      Not assigned      Not assigned  43.648690 -79.385440
2      M3A        North York         Parkwoods  43.752420 -79.329242
3      M4A        North York  Victoria Village  43.730600 -79.313265
4      M5A  Downtown Toronto      Harbourfront  43.650295 -79.359166
5      M6A        North York  Lawrence Heights  43.723270 -79.451286
6      M6A        North York    Lawrence Manor  43.723270 -79.451286
7      M7A  Downtown Toronto      Queen's Park  43.661150 -79.391715
8      M8A      Not assigned      Not assigned  43.648690 -79.385440
9      M9A      Queen's Park      Not assigned  43.662299 -79.528195